### ISSUE TITLE
mesage not sending 

### ISSUE THREAD

**Issue by Liyoshinka** [matrix-org/matrix-spec-proposals#3774]
sorry if my english is very very bad i am from ukrainia ![image](https://user-images.githubusercontent.com/101117362/163722753-afb82c35-6b4a-4f6f-9087-99dc8a4b6dac.png)
hwhym messages not sending

**Comment by turt2live** [comment]
I think you're looking for the support team of whichever server you're using. Unfortunately, that isn't here.
