### ISSUE TITLE
Massive issue with spambot recently

### ISSUE THREAD

**Issue by Liyoshinka** [matrix-org/matrix-spec-proposals#3781]
Hello I saw some hackers using a script 
(I leaked their code) which was published under (GPL 2)

https://github.com/Liyoshinka/Matrix-SpamBot

Any idea how to solve this massive bot issue ?

**Comment by Liyoshinka** [comment]
![image](https://user-images.githubusercontent.com/101117362/164332308-57e1a770-c27a-4db2-ab89-061f9adec3d3.png)
here are botted server

**Comment by Liyoshinka** [comment]
![image](https://user-images.githubusercontent.com/101117362/164332468-645c1938-2189-48d4-a337-86fbfa069ebe.png)
someone spammed the chat of BlackArch to 30k people!

**Comment by uhoreg** [comment]
This is not the right place for this issue.

**Comment by Mikaela** [comment]
The tools Matrix provides are practically restricting room membership to users in spaces or knocking from room version 7 which is currently only implemented in Nheko nightly to my knowledge.

* https://www.aminda.eu/blog/english/2021/12/05/matrix-community-abuse-security-by-obscurity.html
