### ISSUE TITLE
Stop blocking onion-routing

### ISSUE THREAD

**Issue by Kreyren** [matrix-org/matrix-spec-proposals#3836]
Currently i can't use onion-services to use any matrix server which is forcing me to use exit node that exposes the traffic to the exit node maintainer and whenever i try to call someone it doesn't work on tor.

Thus proposing to make it possible to deploy matrix servers as onion-services to avoid the need of exit nodes and remove the blocking of tor for P2P and other calls.

**Comment by MTRNord** [comment]
I dont think calls block Tor. It is most likely that Tor browser has webrtc disabled for fingerprinting reasons. Which would not something for spec to solve.

And for the parts about server fed I believe someone recently successfully was able to host a server on Tor. However I don't have the link right now.

**Comment by turt2live** [comment]
This doesn't appear to be a spec issue.

**Comment by Kreyren** [comment]
@turt2live Transfer it to appropriate tracking or tell me where to submit it then..

fwiw seems like a spec issue considering that it's actively filtering tor on all instances without homeserver admins having options to influence it
