### ISSUE TITLE
Delay messages 

### ISSUE THREAD

**Issue by ldicarlo** [matrix-org/matrix-spec-proposals#3867]
**Is your feature request related to a problem? Please describe.**
Sometimes I don't want to send a message right away, and i would rather have it sent later.

**Describe the solution you'd like**
I think currently the best implementation is the one from Google Message, in which a long press on "send" opens a calendar and let you select when the message should be sent.
I don't have enough knowledge to be accurate, but I guess it would imply:
- optionally adding a date, time and timezone to the payload when sending a message,
- ability to fetch  a "future messages queue" to display it on the front
- ability to cancel a message in the queue
 

**Describe alternatives you've considered**
I wanted to try to develop a widget using the widget API, but it is actually too complicated for me for now.

**Additional context**
![Screenshot_20220813-225259.png](https://user-images.githubusercontent.com/15803534/184510424-aeeebd9b-de82-4c56-a822-ea0366b17bed.png)

![Screenshot_20220813-225308.png](https://user-images.githubusercontent.com/15803534/184510428-5f8a2e29-1936-4a0e-a048-bc9ab9fcb9be.png)

![Screenshot_20220813-225317.png](https://user-images.githubusercontent.com/15803534/184510432-3bcc1772-cb80-468e-ba11-b1b8e6579f66.png)

![Screenshot_20220813-225328.png](https://user-images.githubusercontent.com/15803534/184510435-faeb3ab9-7753-422e-b602-2a5e8679021f.png)

Thanks for all the work ! I am using matrix for a year and i love it

**Comment by ldicarlo** [comment]
Hi, 
Oh, I thought it should be an API on the server side and not just a UI component but ok

**Comment by Mikaela** [comment]
I think this should be matrix-spec issue, Elements aren't the only Matrix client and opening an issue there could at best result to a solution where the Element instance has to be running for the delayed message to be delivered instead of queuing it on server.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/matrix-org/matrix-spec/issues/702

**Comment by ldicarlo** [comment]
Indeed, thank you!
