### ISSUE TITLE
Any captcha bot or the option to ask captchas to new users

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [matrix-org/matrix-spec-proposals#3876]
**Is your feature request related to a problem? Please describe.**
Matrix are now full of spam Bots

**Describe the solution you'd like**

I think matrix should offer an option to bring a captcha where the spam bots get filtered.

**Describe alternatives you've considered**

On telegram you have a lot of individual works with multitude of captcha bots and anti spam alternatives, i think matrixc can offer that directley as an administrative option.

**Additional context**

This is not the only bot. It is becoming a real problem for matrix, and i cant find any captcha bot to admin the groups.
![image](https://user-images.githubusercontent.com/12539219/187048134-a7006b76-dc3b-4eec-82f3-93e42c39da7d.png)

**Comment by turt2live** [comment]
This would be better served as a bot at the moment rather than as a spec change.

**Comment by GatoAmarilloBicolor** [comment]
Why? but what will happen with all the spam invasion? :/ i didn't find any bot and the bots are not trustable anywhere they use to get info too.... :/
