### ISSUE TITLE
local recording

### ISSUE THREAD

**Issue by egLanghaus** [matrix-org/matrix-spec-proposals#3877]
Forgive me if this is not the venue for such a thing, but I am just not sure whom to email about this and cannot find documentation that answers my question at matrix.org.

Does a Matrix homeserver, together with an appropriate client, enable one to do "local recording" in the sense offered by podcasting services such as riverside.fm, remotely.fm and zencastr?

Again, forgive me if this is just so benighted that it makes you want to puke - I am sure that my question is replete with misconceptions and category errors, but if you could point me in the right direction then I would really appreciate it!

**Comment by turt2live** [comment]
This seems like a good question for [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org), I think :)
