### ISSUE TITLE
More profile customizability

### ISSUE THREAD

**Issue by whatthemaggie** [matrix-org/matrix-spec-proposals#3950]
I was told this is a spec issue and not a server issue so I'm copying/pasting from my other request

Description:

Is it possible to add more profile customizability? I noticed that Matrix doesn't really have anything on this. I mean specifically profile banners, bios, custom status, etc. Thank you!

**Comment by turt2live** [comment]
This would be covered by https://github.com/matrix-org/matrix-spec-proposals/pull/1769 or similar
