### ISSUE TITLE
I propose to develop our own captcha for user registration confirmation

### ISSUE THREAD

**Issue by gfghjjk** [matrix-org/matrix-spec-proposals#4063]
I propose to develop our own captcha for user registration confirmation

**Comment by turt2live** [comment]
Thanks for your interest in Matrix! We plan to remove all built-in captcha support through use of OIDC, but if there's a detail we're missing then please submit a formal Matrix Spec Change proposal: https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md

More information on our OIDC journey can be found here: https://areweoidcyet.com/
