### ISSUE TITLE
I propose to create news channels in the matrix like in the messenger telegram

### ISSUE THREAD

**Issue by gfghjjk** [matrix-org/matrix-spec-proposals#4066]
I propose to create news channels in the matrix like in the messenger telegram

**Comment by turt2live** [comment]
Thanks for your interest in Matrix! We've already got something like this in the form of Spaces, but if there's a detail we're missing then please submit a formal Matrix Spec Change proposal: https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md
