### ISSUE TITLE
I propose to develop a bot matrix to remove users from rooms for unseemly behavior, insulting users, selling illegal goods, services of whores and prostitutes, porn, erotica, spam.

### ISSUE THREAD

**Issue by gfghjjk** [matrix-org/matrix-spec-proposals#4070]
I propose to develop a bot matrix to remove users from rooms for unseemly behavior, insulting users, selling illegal goods, services of whores and prostitutes, porn, erotica, spam.

**Comment by MTRNord** [comment]
Hi as said before this is not the right place for this issue but to give you a hint https://github.com/the-draupnir-project/Draupnir and https://github.com/matrix-org/mjolnir already exist for moderation purposes.

**Comment by KitsuneRal** [comment]
@gfghjjk - судя по вашей активности в других репо GitHub, вы русскоговорящий. Пожалуйста, прекратите спам. Вам уже ответили ссылками на документ, объясняющий как писать proposals в этом проекте; но вы продолжаете отправлять однострочники, не имеющие общего с конструктивным участием. Если вы будете это делать и дальше, будете забанены.
Translation, ftr: judging by your activity elsewhere in GitHub you speak Russian. Please stop spamming projects. In this repo, you were already directed to the documents describing how to contribute, yet you continue sending one-liner issues that have nothing to do with constructive participation. If you keep doing that, we'll have to ban you.
