### ISSUE TITLE
https://github.com/matrix-org/matrix-spec-proposals/pull/2313/files#r523445447Make this equivalent to tombstone instead.

### ISSUE THREAD

**Issue by SUBINSB90** [matrix-org/matrix-spec-proposals#4236]
Make this equivalent to tombstone instead.

_Originally posted by @erkinalp in https://github.com/matrix-org/matrix-spec-proposals/pull/2313#discussion_r523445447_

**Comment by SUBINSB90** [comment]
https://github.com/matrix-org/matrix-spec-proposals/issues/4236#issue-2723542431

**Comment by KitsuneRal** [comment]
This is incomprehensible.
